### ISSUE TITLE
Very old verison of debian-9

### ISSUE THREAD

**Issue by srlopez** [basdusee/vagrant-linux-routers#2]
Good Job!
But can not get up the vagrant script, because the old debian version.

Can you update the code to recent version?
Thanks

**Comment by basdusee** [comment]
The short answer is: No I can't.

The long answer, is that the technology stack I used six years ago (Vagrant, Virtualbox, Saltstack, Debian) do not cooperate nicely any more in 2023, for the purpose of this repo.
There's an attempt in the new-debian-version branch which you could check out and built on that, but there's too much reparation to do to make this work, and to be honest, the traffic/interest on this repo is too low to justify the effort.

I'll probably do a rewrite in a more modern technology in the near future, if I have time (maybe K8s or GNS3 or Linux network namespaces, something that isn't a headache), or just generate the config files and make it more some sort of a documentary repo. And I'll probably archive this repo in the very near future.

Feel free to experiment more with the new-debian-version branch and I'm allways open to pull requests, but I'm probably not going to improve this repo beyond that. As said, I'll do a remake if popularity increases.

**Comment by basdusee** [comment]
I'll close the issue for now.
